## Booking [/booking]

### Create booking [POST]

+ Request (application/json)

    + Attributes
        + activity_id: 1 (required, number)
        + user_id: 1 (required, number)
        + ticket_details: BookingPriceCategory, BookingPriceCategory (required, array[BookingPriceCategory])
        + emergency_phone_prefix: +36 (string)
        + emergency_phone_number: 70 123 3211 (string)
        + emergency_hotel_info: Hotel room number 101 (string)
        + billing_lastname: Daniel (string)
        + billing_firstname: Test (string)
        + billing_country: Hungary (string)
        + billing_state: Pest (string)
        + billing_other_info: anything (string)
        + billing_zip_code: 1071 (string)
        + billing_city: Budapest (string)
        + billing_address: Test str 11 (string)

+ Response 200 (application/json)

    + Attributes(Booking)

### Show booking [GET /booking/{id}]

+ Parameters
    + id (required, number, `1`) - Booking ID

+ Response 200 (application/json)

    + Attributes(Booking)

### Edit booking [PUT /booking/{id}]

+ Parameters
    + id (required, number, `1`) - Booking ID

+ Request (application/json)

    + Attributes
        + activity_id: 1 (required, number)
        + user_id: 1 (required, number)
        + date: 2018-12-01 (required, date)
        + checkin_time: 08:00 (required, string)
        + ticket_details: BookingPriceCategory, BookingPriceCategory (required, array[BookingPriceCategory])
        + emergency_phone_prefix: +36 (string)
        + emergency_phone_number: 70 123 3211 (string)
        + emergency_hotel_info: Hotel room number 101 (string)
        + billing_lastname: Daniel (string)
        + billing_firstname: Test (string)
        + billing_country: Hungary (string)
        + billing_state: Pest (string)
        + billing_other_info: anything (string)
        + billing_zip_code: 1071 (string)
        + billing_city: Budapest (string)
        + billing_address: Test str 11 (string)

+ Response 200 (application/json)

    + Attributes(Booking)
