# Data Structures

## Pager

+ total: 4 (number)
+ per_page: 15 (number)
+ current_page: 1 (number)
+ last_page: 1 (number)
+ from: 1 (number)
+ to: 2 (number)

## UserPager (object)
+ Include Pager
+ data: User, User (array[User])

## User (object)
+ id: 7 (number)
+ email: `csaba.gyarmati@clapp.eu` (string)
+ username: `csabagy` (string)
+ full_name: `Csaba Gyarmati` (string)
+ security_question: `Mi a ceg neve?` (string)
+ security_answer`: `ClappCom` (string)
+ website_language_id: 25 (number)
+ country: Country (array[Country])
+ state: `NA` (string)
+ state_other: `NA` (string)
+ zip_code: `1036` (string)
+ city: `Budapest` (string)
+ address: `Lajos utca 74` (string)
+ company_phone_number: `12345678` (string)
+ company_phone_zone: PhoneZone (array[PhoneZone])
+ website: `http:\/\/clapp.eu` (string)
+ avatar: `http:\/\/twistour-be.dev.clapp.eu\/storage\/user_avatar\/n2\/S3\/n2S3GYIIo5aqbxpD2B1PhAkz37LcRVVa.png` (string)
+ introduction: `Ez itt a bemutatkozo szoveg.` (string)
+ company_representative_name: `Company Representative` (string)
+ company_representative_email: `company.representative@clapp.eu` (string)
+ company_representative_phone_number: `301234567` (string)
+ certificate_of_goodstanding: `RUYo5WKdf0jP20L1nerQ2LG7I0OSZqDj.png` (string)
+ payment_type: `bank` (string)
+ paypal_email: `paypal@clapp.eu` (string)
+ bank_name: `Bank` (string)
+ branch_name: `Branch` (string)
+ branch_country: Country (array[Country])
+ branch_state: `BState` (string)
+ branch_zip_code: `1036` (string)
+ branch_city: `Budapest` (string)
+ branch_address: `Lajos utca 74` (string)
+ account_holder_name: `Company Holder` (string)
+ account_number: `123456789` (string)
+ is_iban: true (boolean)
+ swift_code: `1234` (string)
+ tax_id: `4321` (string)
+ routing_number: `5555` (string)
+ additional_information: `Additional info` (string)
+ liability_insurance: `sKKaY33MFwoYSaJFbmTyqyAKPm8edUNY.png` (string)
+ company_representative_phone_zone: PhoneZone (array[PhoneZone])
+ created_at: `2018-01-18 10:46:35` (string)
+ updated_at: `2018-01-18 16:28:11` (string)
+ opening_hours: OpeningHours, OpeningHours (array[OpeningHours])
+ last_name: `Csaba` (string)
+ first_name: `Gyarmati` (string)
+ email_confirmed_at: `2018-01-18 10:46:35` (string)
+ newsletter: false (boolean)
+ terms_accepted: false (boolean)
+ roles: Role, Role (array[Role])
+ website_language: Language (array[Language])
+ languages: Language, Language (array[Language])

## Country (object)
+ id: `HU` (string)

## PhoneZone (object)
+ id: 36 (number)

## Language (object)
+ id: 25 (number)
+ title: `Hungarian` (string)

## Role (object)
+ id: 1 (number)
+ name: `site_owner` (string)
+ display_name: `Site Owner` (string)
+ description: `Site Owner` (string)
+ created_at: `2018-01-18 10:46:35` (string)
+ updated_at: `2018-01-18 10:46:35` (string)

## OpeningHours (object)
+ monday: true (boolean)
+ tuesday: true (boolean)
+ wednesday: true (boolean)
+ thursday: true (boolean)
+ friday: true (boolean)
+ saturday: false (boolean)
+ sunday: false (boolean)
+ start_time (required, object)
    + Include OpeningHourTime
+ end_time (optional, object)
    + Include OpeningHourTime

## OpeningHourTime (object)
+ hours: Hour (array[Hour])
+ minutes: Minute (array[Minute])

## Hour (object)
+ id: 10 (number)
+ text: `10` (string)

## Minute (object)
+ id: 6 (number)
+ text: `30` (string)
