# Data Structures

## Pager

+ total: 4 (number)
+ per_page: 15 (number)
+ current_page: 1 (number)
+ last_page: 1 (number)
+ from: 1 (number)
+ to: 2 (number)

## UserPager (object)
+ Include Pager
+ data: User, User (array[User])

## ActivityPager (object)
+ Include Pager
+ data: Activity, Activity (array[Activity])

## ActivityCategoryPager (object)
+ Include Pager
+ data: ActivityCategory, ActivityCategory (array[ActivityCategory])

## LanguagePager (object)
+ Include Pager
+ data: Language, Language (array[Language])

## User (object)
+ id: 7 (number)
+ email: `csaba.gyarmati@clapp.eu` (string)
+ username: `csabagy` (string)
+ full_name: `Csaba Gyarmati` (string)
+ security_question: `Mi a ceg neve?` (string)
+ security_answer`: `ClappCom` (string)
+ website_language_id: 25 (number)
+ country: Country (array[Country])
+ state: `NA` (string)
+ state_other: `NA` (string)
+ zip_code: `1036` (string)
+ city: `Budapest` (string)
+ address: `Lajos utca 74` (string)
+ company_phone_number: `12345678` (string)
+ company_phone_zone: PhoneZone (array[PhoneZone])
+ website: `http:\/\/clapp.eu` (string)
+ avatar: `http:\/\/twistour-be.dev.clapp.eu\/storage\/user_avatar\/n2\/S3\/n2S3GYIIo5aqbxpD2B1PhAkz37LcRVVa.png` (string)
+ introduction: `Ez itt a bemutatkozo szoveg.` (string)
+ company_representative_name: `Company Representative` (string)
+ company_representative_email: `company.representative@clapp.eu` (string)
+ company_representative_phone_number: `301234567` (string)
+ certificate_of_goodstanding: `RUYo5WKdf0jP20L1nerQ2LG7I0OSZqDj.png` (string)
+ payment_type: `bank` (string)
+ paypal_email: `paypal@clapp.eu` (string)
+ bank_name: `Bank` (string)
+ branch_name: `Branch` (string)
+ branch_country: Country (array[Country])
+ branch_state: `BState` (string)
+ branch_zip_code: `1036` (string)
+ branch_city: `Budapest` (string)
+ branch_address: `Lajos utca 74` (string)
+ account_holder_name: `Company Holder` (string)
+ account_number: `123456789` (string)
+ is_iban: true (boolean)
+ swift_code: `1234` (string)
+ tax_id: `4321` (string)
+ routing_number: `5555` (string)
+ additional_information: `Additional info` (string)
+ liability_insurance: `sKKaY33MFwoYSaJFbmTyqyAKPm8edUNY.png` (string)
+ company_representative_phone_zone: PhoneZone (array[PhoneZone])
+ created_at: `2018-01-18 10:46:35` (string)
+ updated_at: `2018-01-18 16:28:11` (string)
+ opening_hours: OpeningHours, OpeningHours (array[OpeningHours])
+ last_name: `Csaba` (string)
+ first_name: `Gyarmati` (string)
+ email_confirmed_at: `2018-01-18 10:46:35` (string)
+ newsletter: false (boolean)
+ terms_accepted: false (boolean)
+ roles: Role, Role (array[Role])
+ website_language: Language (array[Language])
+ languages: Language, Language (array[Language])

## Country (object)
+ id: `HU` (string)

## PhoneZone (object)
+ id: 36 (number)

## Language (object)
+ id: 25 (number)
+ title: `Hungarian` (string)

## Role (object)
+ id: 1 (number)
+ name: `site_owner` (string)
+ display_name: `Site Owner` (string)
+ description: `Site Owner` (string)
+ created_at: `2018-01-18 10:46:35` (string)
+ updated_at: `2018-01-18 10:46:35` (string)

## OpeningHours (object)
+ monday: true (boolean)
+ tuesday: true (boolean)
+ wednesday: true (boolean)
+ thursday: true (boolean)
+ friday: true (boolean)
+ saturday: false (boolean)
+ sunday: false (boolean)
+ start_time (required, object)
    + Include OpeningHourTime
+ end_time (optional, object)
    + Include OpeningHourTime

## OpeningHourTime (object)
+ hours: Hour (array[Hour])
+ minutes: Minute (array[Minute])

## Hour (object)
+ id: 10 (number)
+ text: `10` (string)

## Minute (object)
+ id: 6 (number)
+ text: `30` (string)

## Activity (object)
+ id: 1 (number)
+ name: `Amazing Budapest` (string)
+ user_id: 1 (number)
+ subtitle: `I!' said the King, 'that saves a world of trouble, you.` (string)
+ main_category: ActivityCategory (array[ActivityCategory])
+ sub_categories: ActivityCategory, ActivityCategory, ActivityCategory (array[ActivityCategory])
+ length_of_activity
    + Include ActivityLength
+ unspecified: true (boolean)
+ description: `Alice's shoulder as he wore his crown over the list, feeling very glad that it was all about, and make THEIR eyes bright and eager with many a strange tale, perhaps even with the Queen, pointing to.` (string)
+ detailed_itinerary: `Tell her to wink with one of the garden, where Alice could think of nothing better to say 'creatures,' you see, because some of YOUR adventures.' 'I could tell you my adventures--beginning from this.` (string)
+ faq: Faq, Faq, Faq (array[Faq])
+ what_to_bring: `Footman, 'and that for the baby, it was good practice to say whether the blows hurt it or not. 'Oh, PLEASE mind what you're talking about,' said Alice. 'Of course twinkling begins with an important.` (string)
+ good_to_know: `Alice: 'I don't know the way the people that walk with their heads!' and the turtles all advance! They are waiting on the glass table and the Mock Turtle, 'but if they do, why then they're a kind of.` (string)
+ languages: Language, Language (array[Language])
+ cancellation_policy: CancellationPolicy (array[CancellationPolicy])
+ min_participant: 0 (number)
+ max_participant: 0 (number)
+ extra_info
    + Include ActivityExtraInfo
+ free_sale: `true` (string)
+ country: Country (array[Country])
+ timezone: TimeZone (array[TimeZone])
+ location: `Budapest lajos utca 64` (string)
+ coordinates
    + Include Coordinate
+ exact_meeting_point: `A sarkon.` (string)
+ phone_zone: PhoneZone (array[PhoneZone])
+ phone_number: `123456789` (string)
+ checkin_times: OpeningHours, OpeningHours (array[OpeningHours])
+ opening_hours: OpeningHours, OpeningHours (array[OpeningHours])
+ price_categories: PriceCategory, PriceCategory (array[PriceCategory])
+ price_includes: `Include` (string)
+ price_not_includes: `Not include` (string)
+ extra_options: PriceCategory (array[PriceCategory])
+ video_url: `https:\/\/youtu.be\/1i-ztAmPs4s` (string)
+ cover: `http:\/\/twistour-be.dev.clapp.eu\/storage\/activity_cover\/85\/eo\/85eoGBwQmW9T8oynVSCr5HPUMZB7waYj.png` (string)
+ media: GalleryImage, GalleryImage, GalleryImage, GalleryImage, GalleryImage, GalleryImage, GalleryImage (array[GalleryImage])
+ completion_status: `pricing` (enum[string])
    + Members
        + information
        + location
        + availability
        + pricing
        + media
        + completed
+ review_status: `pending` (enum[string])
    + Members
        + pending
        + approved
        + refused
+ is_active: false (boolean)
+ current_user
    + Include ActivityMetadata

## Booking (object)
+ id: 1 (number)
+ activity_id: 1 (number)
+ user_id: 1 (number)
+ date: 2018-12-01 (date)
+ checkin_time: 08:00:00 (string)
+ status: `pending` (enum[string])
    + Members
        + created
        + pending
        + approved
        + refused
        + expired
+ activity_details: Activity (array[Activity])
+ emergency_phone_prefix: +36 (required, string)
+ emergency_phone_number: 70 123 3211 (required, string)
+ emergency_hotel_info: Hotel room number 101 (required, string)
+ billing_lastname: Daniel (required, string)
+ billing_firstname: Test (required, string)
+ billing_country: Hungary (required, string)
+ billing_state: Pest (required, string)
+ billing_other_info: anything (required, string)
+ billing_zip_code: 1071 (required, string)
+ billing_city: Budapest (required, string)
+ billing_address: Test str 11 (required, string)

## Payment (object)
+ id: 15
+ booking_id: 17
+ status: paid
+ invoice_number: 5b56ee308dedd
+ paypal_id: PAY-801922490G564861BLNLO4II
+ amount: 72.44
+ authorization_id: 9N364551789727030
+ created_at: 2018-07-24 09:15:28
+ updated_at: 2018-07-24 09:15:28

## ActivityCategory (object)
+ id: 5 (number)
+ title: `Family` (string)

## ActivityLength (object)
+ days: 1 (number)
+ hours: 6 (number)
+ minutes: 15 (number)

## Faq (object)
+ question: `Faq question` (string)
+ answer: `Faq answer` (string)

## CancellationPolicy (object)
+ id (enum[string])
    + Members
        + strict
        + moderate
        + flexible

+ title: `Strict` (string)

## ActivityExtraInfo (object)
+ open_bar: false (boolean)
+ adults_only: false (boolean)
+ private_tour: false (boolean)
+ kids_friendly: false (boolean)
+ cruise_ship_ready: true (boolean)
+ vegan_food_available: false (boolean)
+ wheelchair_accessible: true (boolean)
+ hotel_transfer_included: false (boolean)
+ mobile_voucher_accepted: false (boolean)
+ hotel_transfer_available: false (boolean)

## Coordinate (object)
+ latitude: `47.5308788` (string)
+ longitude: `19.0396924` (string)

## PriceCategory (object)
+ name: `Ticket` (string)
+ note: `Note` (string)
+ net_price: 15 (number)
+ retail_price: 10 (number)

## BookingPriceCategory (object)
+ name: `Ticket` (string)
+ note: `Note` (string)
+ net_price: 15 (number)
+ retail_price: 10 (number)
+ amount_booked: 1 (number)

## GalleryImage (object)
+ id: 1 (number)
+ filename: `RJtSjjPXBAirKTFH3on3E7nsNA4cYPlc.png` (string)
+ title: `` (string)
+ description: `` (string)
+ activity_id: 1 (number)
+ url: `http:\/\/twistour-be.dev.clapp.eu\/storage\/activity_media\/RJ\/tS\/RJtSjjPXBAirKTFH3on3E7nsNA4cYPlc.png` (string)

## TimeZone (object)
+ id: `Europe\/Budapest` (string)

## ActivityMetadata (object)
+ marked_favourite: false (boolean)
