## User  [/user]

### User list [GET]

+ Response 404 (application/json)
+ Response 200 (application/json)

    + Attributes(UserPager)

### Create user [POST]

+ Request (application/json)

    + Body

            {
                "username": "csabagy" (required, string),
                "email": "csaba.gyarmati@clapp.eu" (required, string),
                "password": "newpasword" (required, string),
                "terms_accepted": true (required, boolean)
            }

+ Response 201

    + Body

            {
                "token": "auth token"
            }

## User Details [/user/{id}]

+ Parameters
    + id (required, number, `1`) - User ID or me

### User detail [GET]

+ Response 200 (application/json)

    + Attributes(User)

### Edit user data [PUT]

+ Request (application/json)

    + Body

            {
                "username": "csabagy" (string),
                "password": "newpasword" (optional, string)
            }

+ Response 200 (application/json)

    + Attributes(UserPager)
