## Activity Media [/activity/{id}/media]

+ Parameters
    + id (required, number, `1`) - Activity ID

### Upload media [POST]

+ Request (multipart/form-data, boundary=AaB03x)

    + Headers

            Content-Length: $requestlen

    + Body

            --AaB03x
            content-disposition: form-data; name="file"; filename="$filename"
            Content-Type: $mimetype
            Content-Transfer-Encoding: binary

            $binarydata
            --AaB03x--

+ Response 404 (application/json)
+ Response 415 (application/json)
+ Response 200 (application/json)

    + Attributes(Activity)
